spring:
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    url: r2dbc:h2:mem://./testdb
    username: sa
    password: testdb
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: detect
  profiles:
    default: local
  webflux:
    base-path: /userApi

